package orderservice.server.core.po;
// Generated 2018-7-2 14:30:12 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test3 generated by hbm2java
 */
@Entity
@Table(name = "test3", catalog = "hospwx")
public class Test3 implements java.io.Serializable {

	private Integer autocid;
	private String vfiled;

	public Test3() {
	}

	public Test3(String vfiled) {
		this.vfiled = vfiled;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "autocid", unique = true, nullable = false)
	public Integer getAutocid() {
		return this.autocid;
	}

	public void setAutocid(Integer autocid) {
		this.autocid = autocid;
	}

	@Column(name = "vfiled", length = 50)
	public String getVfiled() {
		return this.vfiled;
	}

	public void setVfiled(String vfiled) {
		this.vfiled = vfiled;
	}

}
